[package]
name = "symphony"
version = "0.1.0"
authors = ["Lequn Chen <chenlequn22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
cxx = "0.5"

[build-dependencies]
cxx-build = "0.5"
