on: [push]

name: CI

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache libtensorflow_cc
        id: cache-libtensorflow_cc
        uses: actions/cache@v2
        with:
          path: libtensorflow_cc-v2.3.1-gpu
          key: libtensorflow_cc-v2.3.1-gpu
      - name: Downlaod libtensorflow_cc
        if: steps.cache-libtensorflow_cc.outputs.cache-hit != 'true'
        run: ./download-libtensorflow_cc.sh
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
